//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.WCF
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PhotoDTO", Namespace = "http://schemas.datacontract.org/2004/07/MyPhotos.WCF", IsReference = true)]
    public partial class PhotoDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        private string NameField;

        private string PathField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IMyPhotosWcf")]
public interface IMyPhotosWcf
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/CreatePhoto", ReplyAction = "http://tempuri.org/IMyPhotosWcf/CreatePhotoResponse")]
    System.Guid CreatePhoto(string path, string name, string @event, string place, string[] persons);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/CreatePhoto", ReplyAction = "http://tempuri.org/IMyPhotosWcf/CreatePhotoResponse")]
    System.Threading.Tasks.Task<System.Guid> CreatePhotoAsync(string path, string name, string @event, string place, string[] persons);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/GetAllPhotos", ReplyAction = "http://tempuri.org/IMyPhotosWcf/GetAllPhotosResponse")]
    MyPhotos.WCF.PhotoDTO[] GetAllPhotos();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/GetAllPhotos", ReplyAction = "http://tempuri.org/IMyPhotosWcf/GetAllPhotosResponse")]
    System.Threading.Tasks.Task<MyPhotos.WCF.PhotoDTO[]> GetAllPhotosAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/AddCustomProperty", ReplyAction = "http://tempuri.org/IMyPhotosWcf/AddCustomPropertyResponse")]
    void AddCustomProperty(string id, string name, string value);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/AddCustomProperty", ReplyAction = "http://tempuri.org/IMyPhotosWcf/AddCustomPropertyResponse")]
    System.Threading.Tasks.Task AddCustomPropertyAsync(string id, string name, string value);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/GetFilteredPhotos", ReplyAction = "http://tempuri.org/IMyPhotosWcf/GetFilteredPhotosResponse")]
    MyPhotos.WCF.PhotoDTO[] GetFilteredPhotos(string property, string value);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/GetFilteredPhotos", ReplyAction = "http://tempuri.org/IMyPhotosWcf/GetFilteredPhotosResponse")]
    System.Threading.Tasks.Task<MyPhotos.WCF.PhotoDTO[]> GetFilteredPhotosAsync(string property, string value);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/GetAllPropertiesAsStrings", ReplyAction = "http://tempuri.org/IMyPhotosWcf/GetAllPropertiesAsStringsResponse")]
    string[] GetAllPropertiesAsStrings();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyPhotosWcf/GetAllPropertiesAsStrings", ReplyAction = "http://tempuri.org/IMyPhotosWcf/GetAllPropertiesAsStringsResponse")]
    System.Threading.Tasks.Task<string[]> GetAllPropertiesAsStringsAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyPhotosWcfChannel : IMyPhotosWcf, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyPhotosWcfClient : System.ServiceModel.ClientBase<IMyPhotosWcf>, IMyPhotosWcf
{

    public MyPhotosWcfClient()
    {
    }

    public MyPhotosWcfClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public MyPhotosWcfClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public MyPhotosWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public MyPhotosWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public System.Guid CreatePhoto(string path, string name, string @event, string place, string[] persons)
    {
        return base.Channel.CreatePhoto(path, name, @event, place, persons);
    }

    public System.Threading.Tasks.Task<System.Guid> CreatePhotoAsync(string path, string name, string @event, string place, string[] persons)
    {
        return base.Channel.CreatePhotoAsync(path, name, @event, place, persons);
    }

    public MyPhotos.WCF.PhotoDTO[] GetAllPhotos()
    {
        return base.Channel.GetAllPhotos();
    }

    public System.Threading.Tasks.Task<MyPhotos.WCF.PhotoDTO[]> GetAllPhotosAsync()
    {
        return base.Channel.GetAllPhotosAsync();
    }

    public void AddCustomProperty(string id, string name, string value)
    {
        base.Channel.AddCustomProperty(id, name, value);
    }

    public System.Threading.Tasks.Task AddCustomPropertyAsync(string id, string name, string value)
    {
        return base.Channel.AddCustomPropertyAsync(id, name, value);
    }

    public MyPhotos.WCF.PhotoDTO[] GetFilteredPhotos(string property, string value)
    {
        return base.Channel.GetFilteredPhotos(property, value);
    }

    public System.Threading.Tasks.Task<MyPhotos.WCF.PhotoDTO[]> GetFilteredPhotosAsync(string property, string value)
    {
        return base.Channel.GetFilteredPhotosAsync(property, value);
    }

    public string[] GetAllPropertiesAsStrings()
    {
        return base.Channel.GetAllPropertiesAsStrings();
    }

    public System.Threading.Tasks.Task<string[]> GetAllPropertiesAsStringsAsync()
    {
        return base.Channel.GetAllPropertiesAsStringsAsync();
    }
}
